[workspace]
members = [
    "./bls-snark-setup",
    "./powersoftau",
    "./phase2",
    "./snark-utils",
    "./test-helpers",
]

[patch."https://github.com/scipr-lab/zexe"]
algebra = { version = "0.1.0", package = "algebra", git = "https://github.com/nimiq/zexe", branch = "paberr/constant-serialized-size" }
fft = { package = "ff-fft", git = "https://github.com/nimiq/zexe", branch = "paberr/constant-serialized-size" }
groth16 = { package = "groth16", git = "https://github.com/nimiq/zexe", branch = "paberr/constant-serialized-size" }
r1cs-core = { package = "r1cs-core", git = "https://github.com/nimiq/zexe", branch = "paberr/constant-serialized-size" }
r1cs-std = { package = "r1cs-std", git = "https://github.com/nimiq/zexe", branch = "paberr/constant-serialized-size" }
crypto-primitives = { package = "crypto-primitives", git = "https://github.com/nimiq/zexe", branch = "paberr/constant-serialized-size" }
