[workspace]
members = [
    "./powersoftau",
    # "./phase2", # temporarily disabled
    "./snark-utils",
    "./test-helpers",
]

[patch.crates-io]
algebra = { package = "algebra", git = "https://github.com/gakonst/zexe", branch = "serde-uncompressed" }
ff-fft = { package = "ff-fft", git = "https://github.com/gakonst/zexe", branch = "serde-uncompressed" }
