[workspace]
members = [
    "./powersoftau",
    "./phase2",
    "./snark-utils",
    "./test-helpers",
]

[patch.crates-io]
algebra = { package = "algebra", git = "https://github.com/gakonst/zexe", branch = "serde-uncompressed" }
ff-fft = { package = "ff-fft", git = "https://github.com/gakonst/zexe", branch = "serde-uncompressed" }
groth16 = { package = "groth16", git = "https://github.com/gakonst/zexe", branch = "serde-uncompressed" }
r1cs-core = { package = "r1cs-core", git = "https://github.com/gakonst/zexe", branch = "serde-uncompressed" }