[workspace]
members = [
    "./bls-snark-setup",
    "./powersoftau",
    "./phase2",
    "./snark-utils",
    "./test-helpers",
]

[patch."https://github.com/scipr-lab/zexe"]
algebra = { version = "0.1.0", package = "algebra", git = "https://github.com/gakonst/zexe", branch = "constraint-counter" }
ff-fft = { package = "ff-fft", git = "https://github.com/gakonst/zexe", branch = "constraint-counter" }
groth16 = { package = "groth16", git = "https://github.com/gakonst/zexe", branch = "constraint-counter" }
r1cs-core = { package = "r1cs-core", git = "https://github.com/gakonst/zexe", branch = "constraint-counter" } 
r1cs-std = { package = "r1cs-std", git = "https://github.com/gakonst/zexe", branch = "constraint-counter" } 
gm17 = { package = "gm17", git = "https://github.com/gakonst/zexe", branch = "constraint-counter" } 
crypto-primitives = { package = "crypto-primitives", git = "https://github.com/gakonst/zexe", branch = "constraint-counter" } 