[workspace]
members = [
    "./powersoftau",
    "./phase2"
]

[patch.crates-io]
pairing_ce = { git = "https://github.com/gakonst/pairing", branch = "expose-points"  }
bellman_ce = { git = "https://github.com/matter-labs/bellman", branch = "master"  }
