version: 2
jobs:
  build:
    docker:
      - image: circleci/rust
    environment:
      CARGO_HOME: /home/circleci/.cargo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            cargo install cargo-audit
            rustup component add clippy
      - run:
          name: Build
          command: cargo build --all-features
      - run:
          name: Test
          command: cargo test --all --all-features
      - run:
          name: Test chunked powers of tau Groth16
          command: cd phase1-cli && bash ./phase1_chunked.sh groth16
      - run:
          name: Test full powers of tau Groth16
          command: cd phase1-cli && bash ./phase1_full.sh groth16
      - run:
          name: Test chunked powers of tau Groth16
          command: cd phase1-cli && bash ./phase1_chunked.sh marlin
      - run:
          name: Test full powers of tau Groth16
          command: cd phase1-cli && bash ./phase1_full.sh marlin
      - name: Install WASM
          run: |
            rustup target add wasm32-unknown-unknown --toolchain nightly
            cargo install wasm-bindgen-cli
            cargo update -p wasm-bindgen
      - name: Run WASM tests
          run: |
            cd phase1-wasm
            cargo test --release --target wasm32-unknown-unknown --no-default-features --features wasm
      - run:
          name: Check Style
          command: |
            cargo fmt --all -- --check
            cargo clippy --all-targets --all-features -- -D warnings
      - run:
          name: Audit Dependencies
          command: cargo audit --ignore RUSTSEC-2020-0006
