[package]
name = "snark-utils"
version = "0.1.0"
authors = ["Georgios Konstantopoulos <me@gakonst.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.11"
zexe_algebra = { package = "algebra", version = "0.1.0", features = ["parallel"] }
zexe_fft = { package = "ff-fft", version = "0.1.0", features = ["parallel"] }
rayon = "1.3.0"

# crypto lower-level crates
rand = "0.7.3"
rand_chacha = "0.2.1"
typenum = "1.11.2"
rust-crypto = "0.2"
crossbeam = "0.7.3"
num_cpus = "1.12.0"
blake2 = "0.8.1"
zexe_r1cs_core = { package = "r1cs-core", git = "https://github.com/gakonst/zexe", branch = "serde-uncompressed" }

[dev-dependencies]
criterion = "0.3.1"
test-helpers = { path = "../test-helpers" }
powersoftau = { path = "../powersoftau" }
zexe_algebra = { package = "algebra", version = "0.1.0", features = ["parallel", "full"] }

[[bench]]
name = "math"
harness = false
[[bench]]
name = "io"
harness = false
