name: CLI
on:
  pull_request:
  push:
    branches:
      - master
env:
  RUST_BACKTRACE: 1

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -Dwarnings
    strategy:
      matrix:
        rust:
          - stable
#          - nightly
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Rust (${{ matrix.rust }})
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Run phase1 chunked groth16
        run: cd phase1-cli && ./scripts/phase1_chunked.sh groth16

      - name: Run phase1 full groth16
        run: cd phase1-cli && ./scripts/phase1_full.sh groth16

      - name: Run phase1 chunked marlin
        run: cd phase1-cli && ./scripts/phase1_chunked.sh marlin

      - name: Run phase1 full marlin
        run: cd phase1-cli && ./scripts/phase1_full.sh marlin

